[sources.log_files]
type = "file"
include = ["/home/Moengage-Consumer-v3/logs/debug/*", "/home/Moengage-Consumer-v3/logs/error/*"]
exclude = ["*.json"]
ignore_older_secs = 600
read_from = "end"

[sinks.destination_server]
type = "socket"
inputs = ["log_files"]
address = "10.0.3.165:8688"
mode = "tcp"
encoding.codec = "text"
