[sources.consumer_logs]
type = "socket"
address = "0.0.0.0:8688"
mode = "tcp"

[transforms.add_ip]
type = "remap"
inputs = ["consumer_logs"]
source = '''
.host_ip = .host
'''

[sinks.local_files]
type = "file"
inputs = ["add_ip"]  
path = "/%Y-%m-%d.gz"
encoding.codec = "json"  
compression = "gzip"
